[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "wodoo"
author = "ACSONE SA/NV"
author-email = "info@acsone.eu"
classifiers = ["License :: OSI Approved :: MIT License", "Framework :: Odoo"]
requires = ["tomli", "setuptools-odoo", "wheel"]

[tool.flit.scripts]
wodoo = "wodoo.cli:main"
