[build-system]
requires = ["flit_core@git+https://github.com/sbidoul/flit.git@d68674b#subdirectory=flit_core"]  # >=3.2,<4
build-backend = "flit_core.buildapi"

[project]
name = "wodoo"
description = "wodoo - Next Gen Odoo Addons packager"
version = "0.9.0"
authors = [
    {name = "Stéphane Bidoul", email = "stephane.bidoul@acsone.eu"}
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Framework :: Odoo",
]
requires-python = ">=3.6"
dependencies = [
    "importlib_metadata;python_version<'3.8'",
    "setuptools-odoo",
    "tomli",
    "wheel",
]

[project.scripts]
wodoo = "wodoo.cli:main"

[tool.isort]
profile = 'black'

[tool.mypy]
strict = true
