[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "wodoo"
author = "ACSONE SA/NV"
author-email = "info@acsone.eu"
classifiers = ["License :: OSI Approved :: MIT License"]
requires = ["pep517", "pytoml", "setuptools-odoo", "wheel"]

[tool.flit.scripts]
wodoo = "wodoo.cli:main"
