[build-system]
requires = ["flit_core@git+https://github.com/takluyver/flit.git@master#subdirectory=flit_core"]  # >=3.4,<4
build-backend = "flit_core.buildapi"

[project]
name = "wodoo"
description = "wodoo - build backend for Odoo addons"
version = "0.9.0a"
authors = [
    {name = "Stéphane Bidoul", email = "stephane.bidoul@acsone.eu"}
]
classifiers = [
    "Development Status :: Alpha",
    "License :: OSI Approved :: MIT License",
    "Framework :: Odoo",
]
requires-python = ">=3.6"
dependencies = [
    "importlib_metadata;python_version<'3.8'",
    # "setuptools-odoo>=3.0",
    "setuptools-odoo @ git+https://github.com/acsone/setuptools-odoo",
    "tomli",
    "wheel",
]
scripts = {wodoo = "wodoo.cli:main"}

[tool.isort]
profile = 'black'

[tool.mypy]
strict = true
